const initialState = {
  categories: [
    { id: 'bed', name: 'Bed' },
    { id: 'chair', name: 'Chair' },
    { id: 'sofa', name: 'Sofa' },
    { id: 'table', name: 'Table' },
    { id: 'dining', name: 'Dining' },
  ],
  products: [
    {
      id: 'aenean-ru-bristique-1',
      name: 'Aenean Ru Bristique 1',
      category: 'bed',
      image: '/images/furnitures/f-1.png',
      price: 30,
      oldPrice: '$35',
      myRating: 3,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      toFavorite: true,
      toCompare: true,
    },
    {
      id: 'aenean-ru-bristique-2',
      name: 'Aenean Ru Bristique 2',
      category: 'bed',
      image: '/images/furnitures/f-2.png',
      price: 30,
      oldPrice: '',
      stars: 2,
      myRating: null,
      promo: 'sale',
      newFurniture: true,
      toFavorite: true,
      toCompare: false,
    },
    {
      id: 'aenean-ru-bristique-3',
      name: 'Aenean Ru Bristique 3',
      category: 'bed',
      image: '/images/furnitures/f-3.png',
      price: 30,
      oldPrice: '$38',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      toFavorite: false,
      toCompare: true,
    },
    {
      id: 'aenean-ru-bristique-4',
      name: 'Aenean Ru Bristique 4',
      category: 'bed',
      image: '/images/furnitures/f-4.png',
      price: 30,
      oldPrice: '',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      toFavorite: false,
      toCompare: false,
    },
    {
      id: 'aenean-ru-bristique-5',
      name: 'Aenean Ru Bristique 5',
      category: 'bed',
      image: '/images/furnitures/f-5.png',
      price: 30,
      oldPrice: '$45',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-6',
      name: 'Aenean Ru Bristique 6',
      category: 'bed',
      image: '/images/furnitures/f-6.png',
      price: 30,
      oldPrice: '$37',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-7',
      name: 'Aenean Ru Bristique 7',
      category: 'bed',
      image: '/images/furnitures/f-7.png',
      price: 30,
      oldPrice: '',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-8',
      name: 'Aenean Ru Bristique 8',
      category: 'bed',
      image: '/images/furnitures/f-8.png',
      price: 30,
      oldPrice: '',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-9',
      name: 'Aenean Ru Bristique 9',
      category: 'bed',
      image: '/images/furnitures/f-9.png',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-10',
      name: 'Aenean Ru Bristique 10',
      category: 'bed',
      image: '/images/furnitures/f-10.png',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-11',
      name: 'Aenean Ru Bristique 11',
      category: 'bed',
      image: '/images/furnitures/f-11.png',
      price: 30,
      oldPrice: '',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-12',
      name: 'Aenean Ru Bristique 12',
      category: 'bed',
      image: '/images/furnitures/f-12.png',
      price: 30,
      oldPrice: '',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-13',
      name: 'Aenean Ru Bristique 13',
      category: 'bed',
      image: '/images/furnitures/f-1.png',
      price: 30,
      oldPrice: '',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-14',
      name: 'Aenean Ru Bristique 14',
      category: 'bed',
      image: '/images/furnitures/f-2.png',
      price: 30,
      oldPrice: '$35',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-15',
      name: 'Aenean Ru Bristique 15',
      category: 'bed',
      image: '/images/furnitures/f-3.png',
      price: 30,
      oldPrice: '',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-16',
      name: 'Aenean Ru Bristique 16',
      category: 'bed',
      image: '/images/furnitures/f-4.png',
      price: 30,
      oldPrice: '',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-17',
      name: 'Aenean Ru Bristique 17',
      category: 'bed',
      image: '/images/furnitures/f-5.png',
      price: 30,
      oldPrice: '',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-18',
      name: 'Aenean Ru Bristique 18',
      category: 'bed',
      image: '/images/furnitures/f-6.png',
      price: 30,
      oldPrice: '',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-19',
      name: 'Aenean Ru Bristique 19',
      category: 'bed',
      image: '/images/furnitures/f-7.png',
      price: 30,
      oldPrice: '$37',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-20',
      name: 'Aenean Ru Bristique 20',
      category: 'bed',
      image: '/images/furnitures/f-8.png',
      price: 30,
      oldPrice: '$50',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-21',
      name: 'Aenean Ru Bristique 21',
      category: 'bed',
      image: '/images/furnitures/f-9.png',
      price: 30,
      oldPrice: '',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-22',
      name: 'Aenean Ru Bristique 22',
      category: 'bed',
      image: '/images/furnitures/f-10.png',
      price: 30,
      oldPrice: '',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-23',
      name: 'Aenean Ru Bristique 23',
      category: 'bed',
      image: '/images/furnitures/f-11.png',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-24',
      name: 'Aenean Ru Bristique 24',
      category: 'bed',
      image: '/images/furnitures/f-12.png',
      price: 30,
      oldPrice: '',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
  ],
  cart: {
    products: [],
  },
  promotions: [
    {
      id: 'sofa',
      image:
        'https://images.pexels.com/photos/3757055/pexels-photo-3757055.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      title: 'guest room',
      strong: 'sofa',
      price: '-20%',
    },
    {
      id: 'chair',
      image:
        'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      title: 'chair',
      strong: 'office',
      subtitle: 'collection',
      price: '$200.000',
    },
    {
      id: 'bed',
      image:
        'https://images.pexels.com/photos/775219/pexels-photo-775219.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      title: 'collection',
      strong: 'special',
      price: 'save up 45% of furniture',
    },
  ],
};

export default initialState;
